name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies with fallback
        timeout-minutes: 10
        run: |
          echo "Cleaning npm cache..."
          npm cache clean --force
          
          echo "Attempting npm ci..."
          if npm ci --no-audit --no-fund --verbose; then
            echo "✅ npm ci succeeded"
          else
            echo "❌ npm ci failed, trying npm install..."
            if npm install --no-audit --no-fund --verbose; then
              echo "✅ npm install succeeded"
            else
              echo "❌ Both npm ci and npm install failed"
              exit 1
            fi
          fi
        env:
          NODE_OPTIONS: --max-old-space-size=6144
          NPM_CONFIG_PROGRESS: true
          NPM_CONFIG_AUDIT: false
          NPM_CONFIG_FUND: false
      
      - name: Verify installation
        run: |
          npm list --depth=0
          npx eslint --version
          npx prettier --version
          npx tsc --version
      
      - name: Run linter
        run: npm run lint
      
      - name: Check formatting
        run: npm run format:check
      
      - name: Type check
        run: npm run typecheck
      
      - name: Run tests
        run: npm run test:run
      
      - name: Build
        run: npm run build
      
      - name: Upload coverage to Codecov
        if: matrix.node-version == 22 && hashFiles('coverage/lcov.info') != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      
      - name: Upload dist artifact
        if: matrix.node-version == 22
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7