name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-20-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-20-npm-
            ${{ runner.os }}-node-20-
      
      - name: Clean npm cache and install dependencies
        run: |
          npm cache clean --force
          npm ci --prefer-offline --no-audit --no-fund --silent
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          NPM_CONFIG_PROGRESS: false
          NPM_CONFIG_AUDIT: false
          NPM_CONFIG_FUND: false
      
      - name: Run tests
        run: npm run test:run
      
      - name: Build
        run: npm run build
      
      - name: Create release archive
        run: |
          mkdir -p release
          cp -r dist package.json README.md LICENSE release/
          cd release
          tar -czf ../mcp-gsheets-${{ github.ref_name }}.tar.gz .
          cd ..
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            mcp-gsheets-${{ github.ref_name }}.tar.gz
          body: |
            ## Release ${{ github.ref_name }}
            
            ### Installation
            
            Download the archive and extract it:
            ```bash
            tar -xzf mcp-gsheets-${{ github.ref_name }}.tar.gz
            npm install
            ```
            
            ### What's Changed
            
            See [commits](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}) for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}